# Spark DataFrames Project Exercise

Let's get some quick practice with your new Spark DataFrame skills, you will be asked some basic questions about some stock market data, in this case Walmart Stock from the years 2012-2017. This exercise will just ask a bunch of questions, unlike the future machine learning exercises, which will be a little looser and be in the form of "Consulting Projects", but more on that later!

For now, just answer the questions and complete the tasks below.

#### Use the walmart_stock.csv file to Answer and complete the  tasks below!

#### Start a simple Spark Session

In [1]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import format_number, corr, round
from pyspark.sql.types import*

Starting Spark application

SparkSession available as 'spark'.
/usr/bin/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

#### Load the Walmart Stock CSV File, have Spark infer the data types.

In [31]:
walmart = spark.read.csv('/HdiNotebooks/walmart_stock.csv', header=True, inferSchema=True)

#### What are the column names?

In [3]:
walmart.columns

['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Adj Close']

#### What does the Schema look like?

In [18]:
walmart.printSchema()

root
 |-- Date: timestamp (nullable = true)
 |-- Open: double (nullable = true)
 |-- High: double (nullable = true)
 |-- Low: double (nullable = true)
 |-- Close: double (nullable = true)
 |-- Volume: integer (nullable = true)
 |-- Adj Close: double (nullable = true)

#### Print out the first 5 columns.

In [19]:
print(walmart.head(5))

[Row(Date=datetime.datetime(2012, 1, 3, 0, 0), Open=59.970001, High=61.060001, Low=59.869999, Close=60.330002, Volume=12668800, Adj Close=52.619234999999996), Row(Date=datetime.datetime(2012, 1, 4, 0, 0), Open=60.209998999999996, High=60.349998, Low=59.470001, Close=59.709998999999996, Volume=9593300, Adj Close=52.078475), Row(Date=datetime.datetime(2012, 1, 5, 0, 0), Open=59.349998, High=59.619999, Low=58.369999, Close=59.419998, Volume=12768200, Adj Close=51.825539), Row(Date=datetime.datetime(2012, 1, 6, 0, 0), Open=59.419998, High=59.450001, Low=58.869999, Close=59.0, Volume=8069400, Adj Close=51.45922), Row(Date=datetime.datetime(2012, 1, 9, 0, 0), Open=59.029999, High=59.549999, Low=58.919998, Close=59.18, Volume=6679300, Adj Close=51.616215000000004)]

#### Use describe() to learn about the DataFrame.

In [21]:
walmart.describe().show()

+-------+------------------+-----------------+-----------------+-----------------+-----------------+-----------------+
|summary|              Open|             High|              Low|            Close|           Volume|        Adj Close|
+-------+------------------+-----------------+-----------------+-----------------+-----------------+-----------------+
|  count|              1258|             1258|             1258|             1258|             1258|             1258|
|   mean| 72.35785375357709|72.83938807631165| 71.9186009594594|72.38844998012726|8222093.481717011|67.23883848728146|
| stddev|  6.76809024470826|6.768186808159218|6.744075756255496|6.756859163732991|  4519780.8431556|6.722609449996857|
|    min|56.389998999999996|        57.060001|        56.299999|        56.419998|          2094900|        50.363689|
|    max|         90.800003|        90.970001|            89.25|        90.470001|         80898100|84.91421600000001|
+-------+------------------+-----------------+-----------------+-----------------+-----------------+-----------------+

## Bonus Question!
#### There are too many decimal places for mean and stddev in the describe() dataframe. Format the numbers to just show up to two decimal places. Pay careful attention to the datatypes that .describe() returns, we didn't cover how to do this exact formatting, but we covered something very similar. [Check this link for a hint](http://spark.apache.org/docs/latest/api/python/pyspark.sql.html#pyspark.sql.Column.cast)

If you get stuck on this, don't worry, just view the solutions.

In [10]:
walmart.withColumn("Open",round(walmart.Open.cast(FloatType()),2)).show(truncate=True)
walmart.withColumn("High",round(walmart.High.cast(FloatType()),2)).show(truncate=True)
walmart.withColumn("Low",round(walmart.Low.cast(FloatType()),2)).show(truncate=True)
walmart.withColumn("Close",round(walmart.Close.cast(FloatType()),2)).show(truncate=True)
walmart.withColumn("Volume",round(walmart.Volume.cast(FloatType()),2)).show(truncate=True)

+-------------------+-----+------------------+------------------+------------------+--------+------------------+
|               Date| Open|              High|               Low|             Close|  Volume|         Adj Close|
+-------------------+-----+------------------+------------------+------------------+--------+------------------+
|2012-01-03 00:00:00|59.97|         61.060001|         59.869999|         60.330002|12668800|52.619234999999996|
|2012-01-04 00:00:00|60.21|         60.349998|         59.470001|59.709998999999996| 9593300|         52.078475|
|2012-01-05 00:00:00|59.35|         59.619999|         58.369999|         59.419998|12768200|         51.825539|
|2012-01-06 00:00:00|59.42|         59.450001|         58.869999|              59.0| 8069400|          51.45922|
|2012-01-09 00:00:00|59.03|         59.549999|         58.919998|             59.18| 6679300|51.616215000000004|
|2012-01-10 00:00:00|59.43|59.709998999999996|             58.98|59.040001000000004| 6907300|         51.494109|
|2012-01-11 00:00:00|59.06|         59.529999|59.040001000000004|         59.400002| 6365600|         51.808098|
|2012-01-12 00:00:00|59.79|              60.0|         59.400002|              59.5| 7236400|51.895315999999994|
|2012-01-13 00:00:00|59.18|59.610001000000004|59.009997999999996|59.540001000000004| 7729300|51.930203999999996|
|2012-01-17 00:00:00|59.87|60.110001000000004|             59.52|         59.849998| 8500000|         52.200581|
|2012-01-18 00:00:00|59.79|         60.029999|         59.650002|60.009997999999996| 5911400|         52.340131|
|2012-01-19 00:00:00|59.93|             60.73|             59.75|60.610001000000004| 9234600|         52.863447|
|2012-01-20 00:00:00|60.75|             61.25|         60.669998|61.009997999999996|10378800|53.212320999999996|
|2012-01-23 00:00:00|60.81|             60.98|60.509997999999996|             60.91| 7134100|         53.125104|
|2012-01-24 00:00:00|60.75|              62.0|             60.75|61.389998999999996| 7362800| 53.54375400000001|
|2012-01-25 00:00:00|61.18|61.610001000000004|61.040001000000004|         61.470001| 5915800| 53.61353100000001|
|2012-01-26 00:00:00| 61.8|             61.84|             60.77|         60.970001| 7436200|         53.177436|
|2012-01-27 00:00:00|60.86|         61.119999|60.540001000000004|60.709998999999996| 6287300|         52.950665|
|2012-01-30 00:00:00|60.47|             61.32|         60.349998|         61.299999| 7636900|53.465256999999994|
|2012-01-31 00:00:00|61.53|             61.57|         60.580002|61.360001000000004| 9761500|53.517590000000006|
+-------------------+-----+------------------+------------------+------------------+--------+------------------+
only showing top 20 rows

+-------------------+------------------+-----+------------------+------------------+--------+------------------+
|               Date|              Open| High|               Low|             Close|  Volume|         Adj Close|
+-------------------+------------------+-----+------------------+------------------+--------+------------------+
|2012-01-03 00:00:00|         59.970001|61.06|         59.869999|         60.330002|12668800|52.619234999999996|
|2012-01-04 00:00:00|60.209998999999996|60.35|         59.470001|59.709998999999996| 9593300|         52.078475|
|2012-01-05 00:00:00|         59.349998|59.62|         58.369999|         59.419998|12768200|         51.825539|
|2012-01-06 00:00:00|         59.419998|59.45|         58.869999|              59.0| 8069400|          51.45922|
|2012-01-09 00:00:00|         59.029999|59.55|         58.919998|             59.18| 6679300|51.616215000000004|
|2012-01-10 00:00:00|             59.43|59.71|             58.98|59.040001000000004| 6907300|         51.494109|
|2012-01-11 00:00:00|         59.060001|59.53|59.040001000000004|         59.400002| 6365600|         51.808098|
|2012-01-12 00:00:00|59.790001000000004| 60.0|         59.400002|              59.5| 7236400|51.895315999999994|
|2012-01-13 00:00:00|             59.18|59.61|59.009997999999996|59.540001000000004| 7729300|51.930203999999996|
|2012-01-17 00:00:00|         59.869999|60.11|             59.52|         59.849998| 8500000|         52.200581|
|2012-01-18 00:00:00|59.790001000000004|60.03|         59.650002|60.009997999999996| 5911400|         52.340131|
|2012-01-19 00:00:00|             59.93|60.73|             59.75|60.610001000000004| 9234600|         52.863447|
|2012-01-20 00:00:00|             60.75|61.25|         60.669998|61.009997999999996|10378800|53.212320999999996|
|2012-01-23 00:00:00|         60.810001|60.98|60.509997999999996|             60.91| 7134100|         53.125104|
|2012-01-24 00:00:00|             60.75| 62.0|             60.75|61.389998999999996| 7362800| 53.54375400000001|
|2012-01-25 00:00:00|             61.18|61.61|61.040001000000004|         61.470001| 5915800| 53.61353100000001|
|2012-01-26 00:00:00|         61.799999|61.84|             60.77|         60.970001| 7436200|         53.177436|
|2012-01-27 00:00:00|60.860001000000004|61.12|60.540001000000004|60.709998999999996| 6287300|         52.950665|
|2012-01-30 00:00:00|         60.470001|61.32|         60.349998|         61.299999| 7636900|53.465256999999994|
|2012-01-31 00:00:00|         61.529999|61.57|         60.580002|61.360001000000004| 9761500|53.517590000000006|
+-------------------+------------------+-----+------------------+------------------+--------+------------------+
only showing top 20 rows

+-------------------+------------------+------------------+-----+------------------+--------+------------------+
|               Date|              Open|              High|  Low|             Close|  Volume|         Adj Close|
+-------------------+------------------+------------------+-----+------------------+--------+------------------+
|2012-01-03 00:00:00|         59.970001|         61.060001|59.87|         60.330002|12668800|52.619234999999996|
|2012-01-04 00:00:00|60.209998999999996|         60.349998|59.47|59.709998999999996| 9593300|         52.078475|
|2012-01-05 00:00:00|         59.349998|         59.619999|58.37|         59.419998|12768200|         51.825539|
|2012-01-06 00:00:00|         59.419998|         59.450001|58.87|              59.0| 8069400|          51.45922|
|2012-01-09 00:00:00|         59.029999|         59.549999|58.92|             59.18| 6679300|51.616215000000004|
|2012-01-10 00:00:00|             59.43|59.709998999999996|58.98|59.040001000000004| 6907300|         51.494109|
|2012-01-11 00:00:00|         59.060001|         59.529999|59.04|         59.400002| 6365600|         51.808098|
|2012-01-12 00:00:00|59.790001000000004|              60.0| 59.4|              59.5| 7236400|51.895315999999994|
|2012-01-13 00:00:00|             59.18|59.610001000000004|59.01|59.540001000000004| 7729300|51.930203999999996|
|2012-01-17 00:00:00|         59.869999|60.110001000000004|59.52|         59.849998| 8500000|         52.200581|
|2012-01-18 00:00:00|59.790001000000004|         60.029999|59.65|60.009997999999996| 5911400|         52.340131|
|2012-01-19 00:00:00|             59.93|             60.73|59.75|60.610001000000004| 9234600|         52.863447|
|2012-01-20 00:00:00|             60.75|             61.25|60.67|61.009997999999996|10378800|53.212320999999996|
|2012-01-23 00:00:00|         60.810001|             60.98|60.51|             60.91| 7134100|         53.125104|
|2012-01-24 00:00:00|             60.75|              62.0|60.75|61.389998999999996| 7362800| 53.54375400000001|
|2012-01-25 00:00:00|             61.18|61.610001000000004|61.04|         61.470001| 5915800| 53.61353100000001|
|2012-01-26 00:00:00|         61.799999|             61.84|60.77|         60.970001| 7436200|         53.177436|
|2012-01-27 00:00:00|60.860001000000004|         61.119999|60.54|60.709998999999996| 6287300|         52.950665|
|2012-01-30 00:00:00|         60.470001|             61.32|60.35|         61.299999| 7636900|53.465256999999994|
|2012-01-31 00:00:00|         61.529999|             61.57|60.58|61.360001000000004| 9761500|53.517590000000006|
+-------------------+------------------+------------------+-----+------------------+--------+------------------+
only showing top 20 rows

+-------------------+------------------+------------------+------------------+-----+--------+------------------+
|               Date|              Open|              High|               Low|Close|  Volume|         Adj Close|
+-------------------+------------------+------------------+------------------+-----+--------+------------------+
|2012-01-03 00:00:00|         59.970001|         61.060001|         59.869999|60.33|12668800|52.619234999999996|
|2012-01-04 00:00:00|60.209998999999996|         60.349998|         59.470001|59.71| 9593300|         52.078475|
|2012-01-05 00:00:00|         59.349998|         59.619999|         58.369999|59.42|12768200|         51.825539|
|2012-01-06 00:00:00|         59.419998|         59.450001|         58.869999| 59.0| 8069400|          51.45922|
|2012-01-09 00:00:00|         59.029999|         59.549999|         58.919998|59.18| 6679300|51.616215000000004|
|2012-01-10 00:00:00|             59.43|59.709998999999996|             58.98|59.04| 6907300|         51.494109|
|2012-01-11 00:00:00|         59.060001|         59.529999|59.040001000000004| 59.4| 6365600|         51.808098|
|2012-01-12 00:00:00|59.790001000000004|              60.0|         59.400002| 59.5| 7236400|51.895315999999994|
|2012-01-13 00:00:00|             59.18|59.610001000000004|59.009997999999996|59.54| 7729300|51.930203999999996|
|2012-01-17 00:00:00|         59.869999|60.110001000000004|             59.52|59.85| 8500000|         52.200581|
|2012-01-18 00:00:00|59.790001000000004|         60.029999|         59.650002|60.01| 5911400|         52.340131|
|2012-01-19 00:00:00|             59.93|             60.73|             59.75|60.61| 9234600|         52.863447|
|2012-01-20 00:00:00|             60.75|             61.25|         60.669998|61.01|10378800|53.212320999999996|
|2012-01-23 00:00:00|         60.810001|             60.98|60.509997999999996|60.91| 7134100|         53.125104|
|2012-01-24 00:00:00|             60.75|              62.0|             60.75|61.39| 7362800| 53.54375400000001|
|2012-01-25 00:00:00|             61.18|61.610001000000004|61.040001000000004|61.47| 5915800| 53.61353100000001|
|2012-01-26 00:00:00|         61.799999|             61.84|             60.77|60.97| 7436200|         53.177436|
|2012-01-27 00:00:00|60.860001000000004|         61.119999|60.540001000000004|60.71| 6287300|         52.950665|
|2012-01-30 00:00:00|         60.470001|             61.32|         60.349998| 61.3| 7636900|53.465256999999994|
|2012-01-31 00:00:00|         61.529999|             61.57|         60.580002|61.36| 9761500|53.517590000000006|
+-------------------+------------------+------------------+------------------+-----+--------+------------------+
only showing top 20 rows

+-------------------+------------------+------------------+------------------+------------------+---------+------------------+
|               Date|              Open|              High|               Low|             Close|   Volume|         Adj Close|
+-------------------+------------------+------------------+------------------+------------------+---------+------------------+
|2012-01-03 00:00:00|         59.970001|         61.060001|         59.869999|         60.330002|1.26688E7|52.619234999999996|
|2012-01-04 00:00:00|60.209998999999996|         60.349998|         59.470001|59.709998999999996|9593300.0|         52.078475|
|2012-01-05 00:00:00|         59.349998|         59.619999|         58.369999|         59.419998|1.27682E7|         51.825539|
|2012-01-06 00:00:00|         59.419998|         59.450001|         58.869999|              59.0|8069400.0|          51.45922|
|2012-01-09 00:00:00|         59.029999|         59.549999|         58.919998|             59.18|6679300.0|51.616215000000004|
|2012-01-10 00:00:00|             59.43|59.709998999999996|             58.98|59.040001000000004|6907300.0|         51.494109|
|2012-01-11 00:00:00|         59.060001|         59.529999|59.040001000000004|         59.400002|6365600.0|         51.808098|
|2012-01-12 00:00:00|59.790001000000004|              60.0|         59.400002|              59.5|7236400.0|51.895315999999994|
|2012-01-13 00:00:00|             59.18|59.610001000000004|59.009997999999996|59.540001000000004|7729300.0|51.930203999999996|
|2012-01-17 00:00:00|         59.869999|60.110001000000004|             59.52|         59.849998|8500000.0|         52.200581|
|2012-01-18 00:00:00|59.790001000000004|         60.029999|         59.650002|60.009997999999996|5911400.0|         52.340131|
|2012-01-19 00:00:00|             59.93|             60.73|             59.75|60.610001000000004|9234600.0|         52.863447|
|2012-01-20 00:00:00|             60.75|             61.25|         60.669998|61.009997999999996|1.03788E7|53.212320999999996|
|2012-01-23 00:00:00|         60.810001|             60.98|60.509997999999996|             60.91|7134100.0|         53.125104|
|2012-01-24 00:00:00|             60.75|              62.0|             60.75|61.389998999999996|7362800.0| 53.54375400000001|
|2012-01-25 00:00:00|             61.18|61.610001000000004|61.040001000000004|         61.470001|5915800.0| 53.61353100000001|
|2012-01-26 00:00:00|         61.799999|             61.84|             60.77|         60.970001|7436200.0|         53.177436|
|2012-01-27 00:00:00|60.860001000000004|         61.119999|60.540001000000004|60.709998999999996|6287300.0|         52.950665|
|2012-01-30 00:00:00|         60.470001|             61.32|         60.349998|         61.299999|7636900.0|53.465256999999994|
|2012-01-31 00:00:00|         61.529999|             61.57|         60.580002|61.360001000000004|9761500.0|53.517590000000006|
+-------------------+------------------+------------------+------------------+------------------+---------+------------------+
only showing top 20 rows

In [13]:
walmart.select(format_number(walmart["Open"].cast("float"), 2).alias("Open"),
format_number(walmart["High"].cast("float"), 2).alias("High"),
format_number(walmart["Low"].cast("float"), 2).alias("Low"),
format_number(walmart["Close"].cast("float"), 2).alias("Close"),
walmart["Volume"].cast("int").alias("Volume")
).show()

+-----+-----+-----+-----+--------+
| Open| High|  Low|Close|  Volume|
+-----+-----+-----+-----+--------+
|59.97|61.06|59.87|60.33|12668800|
|60.21|60.35|59.47|59.71| 9593300|
|59.35|59.62|58.37|59.42|12768200|
|59.42|59.45|58.87|59.00| 8069400|
|59.03|59.55|58.92|59.18| 6679300|
|59.43|59.71|58.98|59.04| 6907300|
|59.06|59.53|59.04|59.40| 6365600|
|59.79|60.00|59.40|59.50| 7236400|
|59.18|59.61|59.01|59.54| 7729300|
|59.87|60.11|59.52|59.85| 8500000|
|59.79|60.03|59.65|60.01| 5911400|
|59.93|60.73|59.75|60.61| 9234600|
|60.75|61.25|60.67|61.01|10378800|
|60.81|60.98|60.51|60.91| 7134100|
|60.75|62.00|60.75|61.39| 7362800|
|61.18|61.61|61.04|61.47| 5915800|
|61.80|61.84|60.77|60.97| 7436200|
|60.86|61.12|60.54|60.71| 6287300|
|60.47|61.32|60.35|61.30| 7636900|
|61.53|61.57|60.58|61.36| 9761500|
+-----+-----+-----+-----+--------+
only showing top 20 rows

In [15]:
walmart.printSchema()

root
 |-- Date: timestamp (nullable = true)
 |-- Open: double (nullable = true)
 |-- High: double (nullable = true)
 |-- Low: double (nullable = true)
 |-- Close: double (nullable = true)
 |-- Volume: integer (nullable = true)
 |-- Adj Close: double (nullable = true)

#### Create a new dataframe with a column called HV Ratio that is the ratio of the High Price versus volume of stock traded for a day.

In [20]:
HVAC_Ratio = walmart.withColumn("HV_Ratio", walmart['High']/walmart['Volume']).show()

+-------------------+------------------+------------------+------------------+------------------+--------+------------------+--------------------+
|               Date|              Open|              High|               Low|             Close|  Volume|         Adj Close|            HV_Ratio|
+-------------------+------------------+------------------+------------------+------------------+--------+------------------+--------------------+
|2012-01-03 00:00:00|         59.970001|         61.060001|         59.869999|         60.330002|12668800|52.619234999999996|4.819714653321546E-6|
|2012-01-04 00:00:00|60.209998999999996|         60.349998|         59.470001|59.709998999999996| 9593300|         52.078475|6.290848613094555E-6|
|2012-01-05 00:00:00|         59.349998|         59.619999|         58.369999|         59.419998|12768200|         51.825539|4.669412994783916E-6|
|2012-01-06 00:00:00|         59.419998|         59.450001|         58.869999|              59.0| 8069400|          51.45922|7.367338463826307E-6|
|2012-01-09 00:00:00|         59.029999|         59.549999|         58.919998|             59.18| 6679300|51.616215000000004|8.915604778943901E-6|
|2012-01-10 00:00:00|             59.43|59.709998999999996|             58.98|59.040001000000004| 6907300|         51.494109|8.644477436914568E-6|
|2012-01-11 00:00:00|         59.060001|         59.529999|59.040001000000004|         59.400002| 6365600|         51.808098|9.351828421515645E-6|
|2012-01-12 00:00:00|59.790001000000004|              60.0|         59.400002|              59.5| 7236400|51.895315999999994| 8.29141562102703E-6|
|2012-01-13 00:00:00|             59.18|59.610001000000004|59.009997999999996|59.540001000000004| 7729300|51.930203999999996|7.712212102001476E-6|
|2012-01-17 00:00:00|         59.869999|60.110001000000004|             59.52|         59.849998| 8500000|         52.200581|7.071764823529412E-6|
|2012-01-18 00:00:00|59.790001000000004|         60.029999|         59.650002|60.009997999999996| 5911400|         52.340131|1.015495466386981E-5|
|2012-01-19 00:00:00|             59.93|             60.73|             59.75|60.610001000000004| 9234600|         52.863447|6.576354146362592...|
|2012-01-20 00:00:00|             60.75|             61.25|         60.669998|61.009997999999996|10378800|53.212320999999996| 5.90145296180676E-6|
|2012-01-23 00:00:00|         60.810001|             60.98|60.509997999999996|             60.91| 7134100|         53.125104|8.547679455011844E-6|
|2012-01-24 00:00:00|             60.75|              62.0|             60.75|61.389998999999996| 7362800| 53.54375400000001|8.420709512685392E-6|
|2012-01-25 00:00:00|             61.18|61.610001000000004|61.040001000000004|         61.470001| 5915800| 53.61353100000001|1.041448341728929...|
|2012-01-26 00:00:00|         61.799999|             61.84|             60.77|         60.970001| 7436200|         53.177436|8.316075414862431E-6|
|2012-01-27 00:00:00|60.860001000000004|         61.119999|60.540001000000004|60.709998999999996| 6287300|         52.950665|9.721183814992126E-6|
|2012-01-30 00:00:00|         60.470001|             61.32|         60.349998|         61.299999| 7636900|53.465256999999994|8.029436027707578E-6|
|2012-01-31 00:00:00|         61.529999|             61.57|         60.580002|61.360001000000004| 9761500|53.517590000000006|6.307432259386365E-6|
+-------------------+------------------+------------------+------------------+------------------+--------+------------------+--------------------+
only showing top 20 rows

#### What day had the Peak High in Price?

In [36]:
#add two [0]'s instead of just one to provide the result only
x= walmart.agg({'High':'max'}).collect()[0][0]
walmart.filter(walmart.High == x).select("Date").show()

+-------------------+
|               Date|
+-------------------+
|2015-01-13 00:00:00|
+-------------------+

#### What is the mean of the Close column?

In [42]:
walmart.agg({"Close": "avg"}).collect()[0][0]

72.38844998012726

#### What is the max and min of the Volume column?

In [44]:
walmart.agg({'Volume':'max'}).collect()[0][0]

80898100

In [45]:
walmart.agg({'Volume':'min'}).collect()[0][0]

2094900

#### How many days was the Close lower than 60 dollars?

In [46]:
walmart.filter(walmart.Close < 60).select("Date").count()

81

#### What percentage of the time was the High greater than 80 dollars ?
#### In other words, (Number of Days High>80)/(Total Days in the dataset)

In [56]:
num_80 = walmart.filter(walmart.High>80).select("Date").count()
count_days = walmart.count()
print(float(num_80)/float(count_days)*100)

9.14149443561

#### What is the Pearson correlation between High and Volume?
#### [Hint](http://spark.apache.org/docs/latest/api/python/pyspark.sql.html#pyspark.sql.DataFrameStatFunctions.corr)

In [57]:
walmart.select(corr("High", "Volume")).show()

+-------------------+
| corr(High, Volume)|
+-------------------+
|-0.3384326061737161|
+-------------------+

#### What is the max High per year?

In [66]:
import datetime
from pyspark.sql.functions import year, month, dayofmonth
walmart.groupBy(year("Date")).agg({'High':'max'}).alias('High_Per_Year').show()

+----------+---------+
|year(Date)|max(High)|
+----------+---------+
|      2015|90.970001|
|      2013|81.370003|
|      2014|88.089996|
|      2012|77.599998|
|      2016|75.190002|
+----------+---------+

#### What is the average Close for each Calendar Month?
#### In other words, across all the years, what is the average Close price for Jan,Feb, Mar, etc... Your result will have a value for each of these months.

In [79]:
walmart.groupBy(month('Date').alias('month')).agg({'Close':'avg'}).sort('month').show()

+-----+-----------------+
|month|       avg(Close)|
+-----+-----------------+
|    1|71.44801958415842|
|    2|  71.306804443299|
|    3|71.77794377570092|
|    4|72.97361900952382|
|    5|72.30971688679247|
|    6| 72.4953774245283|
|    7|74.43971943925233|
|    8|73.02981855454546|
|    9|72.18411785294116|
|   10|71.57854545454543|
|   11| 72.1110893069307|
|   12|72.84792478301885|
+-----+-----------------+

# Great Job!